# Generated by Django 3.1.2 on 2020-11-03 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specializations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerData', models.JSONField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='specializations.specialization', verbose_name='Job specialization')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('userProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='users.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParsedAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answeredOptionWeight', models.IntegerField()),
                ('answerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.answers')),
                ('selectedOptionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='specializations.questionoptions')),
            ],
        ),
    ]
