# Generated by Django 3.1.2 on 2020-11-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='tags',
        ),
        migrations.AlterField(
            model_name='answers',
            name='answerData',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
