# Generated by Django 3.1.2 on 2020-11-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerWeight', models.IntegerField()),
                ('minSalary', models.IntegerField()),
                ('maxSalary', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Jobs.job')),
                ('experience', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('Jobs.job',),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Jobs.job')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('Jobs.job',),
        ),
    ]
