# Generated by Django 3.1.2 on 2020-11-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
        ('Jobs', '0001_initial'),
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='answerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobAnswers', to='answers.answers'),
        ),
        migrations.AddField(
            model_name='job',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='specializations.specialization', verbose_name='Job specialization'),
        ),
    ]
