# Generated by Django 3.1.2 on 2020-11-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(choices=[('SingleChoice', 'Single choice'), ('MultipleChoice', 'Multiple choice'), ('Number', 'Number'), ('FreeText', 'Text')], default='SingleChoice', max_length=15, verbose_name='Type of question group')),
                ('textForEmployer', models.TextField(default='', verbose_name='Text for employer')),
                ('textForCandidate', models.TextField(default='', verbose_name='Text for candidate')),
                ('weight', models.IntegerField()),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='specializations.specialization', verbose_name='Job specialization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.SmallIntegerField(default=1, verbose_name='Option position')),
                ('textForEmployer', models.TextField(default='', verbose_name='Text for employer')),
                ('textForCandidate', models.TextField(default='', verbose_name='Text for candidate')),
                ('weight', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='specializations.questions', verbose_name='Question group name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
