# Generated by Django 3.1.2 on 2020-11-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoptions',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
