# Generated by Django 3.1.2 on 2020-11-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20201103_1926'),
        ('Skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.cv', verbose_name='Link to candidate CV'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.position', verbose_name='Link to position'),
        ),
    ]
